### ISSUE TITLE
SIGABRT: __pthread_kill in libsystem_kernel.dylib

### ISSUE THREAD

**Issue by Constantine-Fry** [bitstadium/HockeySDK-iOS#146]
Hi,

4 month ago we updated HockeyApp from 3.5.5 to 3.6.2. Starting from that release we receive crashes with the following stack trace:
```
Thread 20 Crashed:
1	libsystem_kernel.dylib	__pthread_kill + 8
2	libsystem_pthread.dylib	pthread_kill + 108
3	libsystem_c.dylib	abort + 108
4	libc++abi.dylib	abort_message + 112
5	libc++abi.dylib	default_terminate_handler() + 276
6	libobjc.A.dylib	_objc_terminate() + 152
7	libc++abi.dylib	std::__terminate(void (*)()) + 12
8	libc++abi.dylib	std::terminate() + 60
9	libobjc.A.dylib	objc_terminate + 8
10	libdispatch.dylib	_dispatch_client_callout + 32
11	libdispatch.dylib	_dispatch_queue_drain + 1444
12	libdispatch.dylib	_dispatch_queue_invoke + 128
13	libdispatch.dylib	_dispatch_root_queue_drain + 716
14	libdispatch.dylib	_dispatch_worker_thread3 + 104
15	libsystem_pthread.dylib	_pthread_wqthread + 812
16	libsystem_pthread.dylib	start_wqthread + 0
```

I'm not sure whether it's a bug in our application or in Hockeapp, but we never had such crashes with HockeyApp 3.5.5. Where should I look for the problem?

**Comment by TheRealKerni** [comment]
Can you please provide a full crash report? Thanks.

**Comment by Constantine-Fry** [comment]
Yes, sure.
[Foo](https://www.dropbox.com/s/w056byojh6hmfql/f9fee72d8b9823320b92f8c0ba8b8e18.txt?dl=0) and [Bar](https://www.dropbox.com/s/jkc99m3bzvohgtq/992d31b00c3a91b90eebdc6f35a1f0a3.txt?dl=0)

**Comment by TheRealKerni** [comment]
We'll need some time to analyze this.

**Comment by anlinde** [comment]
Hi again,

here is some more information:

1. This is not a bug in HockeyApp or the SDK
2. `libdispatch` does terminate the app right away if there is an exception occuring during `dispatch_client_callout` and eating the exception, see the source here: http://www.opensource.apple.com/source/libdispatch/libdispatch-228.23/src/object.m (Search for `dispatch_client_callout`)

So this doesn't look to be an effect due to updating the SDK, but rather due to a bug in either your code or Apples code due to an exception occurring.

Hope this helps,
Andreas

**Comment by Constantine-Fry** [comment]
Thank you!
