### ISSUE TITLE
Need 3.6.3 for Xcode 6.3

### ISSUE THREAD

**Issue by tewha** [bitstadium/HockeySDK-iOS#147]
When building in Xcode 3, there's 13 warnings:

`warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]`

These are fixed in develop, but not on a tagged release; it would be good to have a release that fixed these.

**Comment by anlinde** [comment]
You can use a daily build. We have some more changes planned before we release a new version.

https://rink.hockeyapp.net/apps/3e4072df59ed320d3dba9279224f91b9

**Comment by sticksen** [comment]
+1 for tewha´s request.

**Comment by anlinde** [comment]
We can't tag every commit as a new version when we say it is good. We have more changes planned, and also the interface in a component changed, so the next version will not be 3.6.3.

If you don't want to see compiler warnings (the current ones have no negative impact at all), we highly recommend not to integrate the SDK via source but use our binary distribution.

If you want and need the latest fixes before we make an official release, feel free to point your Podfile to the latest commit in the develop branch.

**Comment by smbarne** [comment]
I'd also like to vote for a branch off of 3.6.2 that fixes warnings for Xcode 6.3 that is a stable branched called 3.6.3 for what its worth.

**Comment by tewha** [comment]
I still think the developers should do this, but I understand why they don't want to if they think most people use the binary distribution.

If you want 3.6.2 without the warnings you can do what I did: branch off 3.6.2 and cherry pick fc5f3808ac7eececa271fae7da3b83d410c4a556.

**Comment by ubrett** [comment]
If this was merely an open-source project, I could perhaps understand this rationale. But as a commercial project, introducing a swath of warnings into the projects of users because you want to wait (for an undefined amount of time) for a large release is not good stewardship. The last tagged release for the Hockey SDK was five months ago, and there have been dozens of commits (including the one fixing the warnings) since then. You're putting the desire to hold fast to your personal release schedule ahead of the needs of users.

**Comment by anlinde** [comment]
@ubrett We will release a new version next week. You are also free to use the binary distribution which works just fine and doesn't require you to wait for the SDK to be built every time with your project too.

We will also switch the CocoaPods distribution to use a binary instead of the source in the future, so you'll never have any such issues again.

**Comment by sticksen** [comment]
+1 for ubrett.
Switching to a binary distribution _might_ reduce submitted issues from customers, but that also might be a problem for you in the long run! We are your extended QA test team and some of us (including me) are running apps in a scale that you as HockeyApp might never have the chance to test your software on. 

Please think about what you are doing. Binary = unsexy!

**Comment by ashtom** [comment]
@ubrett One additional comment to what @anlinde said: Most of our competitors do not provide an open source SDK. Instead, they just install a binary framework into your project, so you never see any compiler warnings and have no idea what the SDK are actually doing. It's symptomatic that those competitors get all the love and fame, while we are ridiculed for a few **uncritical** compiler warnings.

The iOS community has fallen a long way and we are now at the point where it actually hurts our product and us personally to provide open source. So we will go binary-only in the near future and you will have a warning-free build process.

**Comment by sticksen** [comment]
@ashtom One additional one from me:

>Most of our competitors do not provide an open source SDK. Instead, they just install a binary framework into your project, so you never see any compiler warnings and have no idea what the SDK are actually doing.

...and they don´t charge you for their service. Why do people pay you for your service? Maybe what you want to abolish is one of your USPs? What would differentiate you from the others (besides charging your users), if you do everything like the others?

To bring it back on track: we´re still talking about one simple `git tag` and one `pod trunk push`. Nothing more. All you had to do for the love of your customers was to execute these two commands.

**Comment by ubrett** [comment]
@ashtom, I certainly hope you didn't perceive my comments as 'ridicule'. That was not the intent at all. But we pay for a professional product and should, I think reasonably, expect professional and timely releases. Hiding warnings behind a binary is not the right solution to that.

**Comment by ashtom** [comment]
@sticksen Our competitors either charge you as well, or provide a free service to uses your data for their business model. We will not remove our open-source SDK, but we will no longer provide a podspec that compiles the code. CocoaPods users apparently expect a warning-free experience and given that Apple has no public roadmap and doesn't inform us in a timely manner before a new release, we have no chance to win this game. We will always be behind a few days with a new release that is properly tested. As @anlinde stated, we are planning to release next week.

We are not talking about a simple `git tag`, but about a responsible testing and release process. You can always fork our repo, branch from master, and fix the very few warnings that only happen because Apple updated their toolchain, not because there is an actual issue in our SDK. We can not and will not release a new version to thousands of developers before our internal quality and review process is completed.

**Comment by ashtom** [comment]
@ubrett Apple released Xcode 6.3 on April 8th and Xcode 6.4 beta on April 13th. In relation to those dates, we consider a new SDK next week as a timely release, especially given the effort to test on 3 architectures, various screen resolutions, compiler configurations, etc., reviewing contributions against potential license issues, and that we don't introduce new bugs that crash your app in production. Apple updated their compiler and added new warnings that only appear because our podspec compiles from source, but there are no actual breaking issues with either release. Once we release a stable version of our SDK, we are responsible and liable for many developers and apps, so we can't just shortcut our release process with a simple `git tag`.

We are always open for feedback, we are developers as you are, and we want stuff as quickly as possible, but there are timing and process restrictions that we have to live with.

**Comment by sticksen** [comment]
@ashtom Well ok, fair enough. What you´re saying seems alright, but goes down another road than what @anlinde said. @anlinde ´s responses were quite brief and didn´t signal that you´re not confident enough (yet) to release a version. 

If you would have said that you need some time to bring us a proper release which handles changes in Xcode 6.3 and 6.4 beta, nobody would have raised his hand. 

Maybe this all was a misunderstanding.
