### ISSUE TITLE
CrashReporter

### ISSUE THREAD

**Issue by hons82** [bitstadium/HockeySDK-iOS#193]
Hi,
is there a reason why this line has been removed from the podspec?
```
ss.ios.vendored_frameworks = 'Vendor/CrashReporter.framework'
```
It has been added because of [this error report](http://support.hockeyapp.net/discussions/problems/15150-hockey-sdk-installation-fails-from-cocoapods)

Now I get this error
```
ld: framework not found CrashReporter
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

thx
~hons

**Comment by anlinde** [comment]
Hi,

are you referring to `HockeySDK.podspec` ? This is using the binary SDK build since version 3.7 instead of using the source. There is an alternate podspec `HockeySDK-Source.podspec` if you want to build it from source.

Can you reproduce this in a sample project that we could take a look at?

Thanks,
Andreas

**Comment by hons82** [comment]
Actually it's an old project, that I just updated using ```pod update``` to the latest HockeySDK and it seems like it was not possible to remove the "Other Linker flag" regarding the crash reporter.

Manually removing it solved the issue and now pod update/install is not re-adding it.

BTW. I tried it with the ```HockeySDK-Source.podspec``` and that one is working too. Thanks 4 the hint/help
