### ISSUE TITLE
“could not inspect application package” Missing framework info.plist

### ISSUE THREAD

**Issue by timward60** [bitstadium/HockeySDK-iOS#210]
Hi,

It seems the CrashReporter.framework in Vendor directory is missing a symbolic link for Info.plist that points to Resource/Info.plist. I am hitting the following issue when launching our application with CrashReporter.framework.

10/13/15 10:39:30.687 PM com.apple.CoreSimulator.CoreSimulatorService[1739]: Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=PackageInspectionFailed, ErrorDescription=Failed to load Info.plist from bundle at path /Users/*****/Library/Developer/CoreSimulator/Devices/31192472-B052-4C26-9A5F-8EC814129EAC/data/Library/Caches/com.apple.mobile.installd.staging/temp.hnQ7NA/extracted/Payload/*******.app/Frameworks/CrashReporter.framework}

Not sure if this is fixed by building a newer version of CrashReporter.framework. Should we continue to use the version bundled in this repository or should we just build directly from PLCrashReporter?

Regards,
Tim

**Comment by lumaxis** [comment]
Hey Tim,

I'm currently trying to verify what is causing this error. Because we haven't seen this in our own apps yet and there also haven't been any other reports so far, can you help in providing steps to reproduce this?

It looks like you are integrating our SDK as source/submodule. Did you follow [these instructions](http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/integrate-hockeyapp-for-ios-as-a-subproject)?
If you could provide a very simple sample project that reproduces the issue, that would be most helpful.

Thanks!

**Comment by lumaxis** [comment]
This was actually a local issue, talked to @timward60 privately and he could resolve it.
