### ISSUE TITLE
Feature request: generate test crashes even in AppStore environment

### ISSUE THREAD

**Issue by bgerstle** [bitstadium/HockeySDK-iOS#212]
Possibly related to #205, but it would be nice to verify that crash reporting works before releasing an app.  We previously did this by having a button in the settings menu which generated a test crash, which used to work for TestFlight builds, but now seems to be a no-op.  Is the recommended workaround for this use case to create our own "generate test crash" method?

**Comment by lumaxis** [comment]
Yes, this broke because Apple changed the way they sign TestFlight builds which in turn broke our AppStore detection.
This will be fixed with our next update. In the meantime you could build our SDK from source (which already contains the fixes) or use some sort of simple crash you come up with yourself. How about a classic, accessing an empty array? `@[][0]` :)

**Comment by bgerstle** [comment]
Thanks for confirming @lumaxis! We're just [calling `__builtin_trap()`](https://github.com/wikimedia/wikipedia-ios/pull/172/files#diff-7692a99959cc1e12009e5e6b3429273bR585) like your implementation does.

**Comment by lumaxis** [comment]
@bgerstle A quick heads-up, I just released [version 3.8.3](https://github.com/bitstadium/HockeySDK-iOS/releases/tag/3.8.3) which should fix the original issue :rocket:
