### ISSUE TITLE
Umbrella header 'HockeySDK.h' not found

### ISSUE THREAD

**Issue by AntiHate** [bitstadium/HockeySDK-iOS#348]
I'd a working build with v3.7.0 with xcode 7, recently I updated to xcode 8 and HockeyApp V4.1.1, now I'm struggling for hours to solve this issue, I'm developing with React Native so I don't have any good understanding of native iOS side.

1: Umbrella header 'HockeySDK.h' not found
2: Could not build module 'HockeySDK'

Following the migration guide and setup tutorial and I'm pretty sure that did exactly what's described. (Step 2.4 & 2.5 objective-C), I'm not using CocoaPods, using default SDK. Framework added in 'Linked Frameworks and Libraries' and also has a entry in 'Framework search path'.

I know there's also React-Native library but to use I've setup CocoaPods, that I'm trying to avoid it for now.

Anything obvious I'm missing here?

**Comment by TroubleMakerBen** [comment]
Hey @AntiHate,
This sounds a lot like a case where your project is in a weird in-between state.
My recommendation would be to "clean" the project up as much as possible, meaning that you delete the working 3.7.0 SDK, your entries for `Framework search path` and `Linked Frameworks and Libraries`, delete all derived data and then, of course, have a project that's failing to build because you've delete the HockeySDK. After that, add the SDK again as described in our readme here. This often solves the problem.
If you have already done this, can you try setting up an empty sample-project and integrate the SDK? If this works, there is definitely an issue with your project setup. Feel free to contact us through [support](https://support.hockeyapp.net) where you can share more info about your project in private.

Best,
Benny

**Comment by AntiHate** [comment]
Hi @TroubleMakerBen, 
Sorry for a late reply and thanks for the detailed post. I tried to do all the things you suggested but unfortunately nothing worked for me.
I've been already trying to build by using 'clean' and removing/adding Hockey Framework and entries from 'Framework search path' and 'Linked Frameworks' but one thing I didn't knew about was removing derived data (Clean build folder), Tried that but still the same error.
Then I also tried with a new project, here are the steps I did.
1, Created Single View Application
2. Build => Succeed
3. Completed steps (2.3 to 2.5) described here
4. Build => Error

After that I deleted Xode and everything related (Derived Data folder and its parent folders), installed Xcode 8 again, repeated steps 1 to 4 stated above, same error, active scheme 'debug' (simulator iOS v10 and Generic iOS devices)

Any more suggestions? Should I contact support for this?

**Comment by Eddpt** [comment]
@AntiHate I'm suffering from the same issue. I'm using `HockeySDK` `4.1.1`, including `subspecs` `AllFeaturesLib`.

Interestingly enough, it is only happening for me in TeamCity. In my own machine it builds fine.

I've found out that TeamCity creates incremental deltas of the changes and transfers them in order to avoid the toll of doing clean checkouts from git every time. In my situation, I VNC'ed to the CI and noticed the symlinks were broken inside the `HockeySDK` folder under `Pods`, even though a clean checkout would show them correctly.

The work around I used was to change a setting in TeamCity:
http://stackoverflow.com/a/30192878/764822

Avoiding the incremental changes from TeamCity made the build green.

This might not be your issue though, but do check if the symlinks are correct for you.

Incorrect:
![screen shot 2016-10-06 at 11 54 35](https://cloud.githubusercontent.com/assets/1426933/19149834/c2b41a58-8bbb-11e6-9b38-460401762b6a.png)

Correct:
![screen shot 2016-10-06 at 11 54 18](https://cloud.githubusercontent.com/assets/1426933/19149849/d5affd2a-8bbb-11e6-92ba-ad2b1a2c62c9.png)

**Comment by TroubleMakerBen** [comment]
Hey @AntiHate 

sorry for letting you hang there without any news.

I just setup a demo-project in React Native and the HockeySDK for iOS integrates just fine. It sounds a lot like you might have wrong paths in your xcode project or something.

I suggest you do the following:
1. Remove the HockeySDK from your project entirely, including the framework added in 'Linked Frameworks and Libraries' and the entry in 'Framework Search Path'.
2. If possible, comment out the import for HockeyApp and the setup code so your project builds fine without the HockeySDK.
3. Copy the `HockeySDK.embeddeframework`-folder into a `Vendor`-folder inside your project's folder. Then just drag-and-drop the `HockeySDK.embeddeframework`-folder in Xcodes project navigator. 
4. Add back the`@import HockeySDK` and uncomment the HA-Setup and build the project.

**Comment by TroubleMakerBen** [comment]
@Eddpt thanks for letting us know about this. It sounds a lot like a mix of a cocoapods-issue and teamcity. We changed the structure of our framework in 4.1.1 and looks like team-city cached some contents from the 4.1.0-SDK. Let us know if you continue to see issues or your workaround doesn't work anymore.

**Comment by AntiHate** [comment]
@Eddpt you pointed out the exact issue, symlinks were broken, actually I've installed MAC on VM, so usually I download/extract stuff in windows and share it on Mac, I didn't noticed that extracting archives in windows thru 7zip breaks symlinks, I extracted the archive in Mac and got a 'build succeed' alert. =)

It looks like a stupid mistake but I really spent couple of days troubleshooting this. Thank you so much @TroubleMakerBen and @Eddpt for your time & support, you were of great help!

**Comment by TroubleMakerBen** [comment]
@AntiHate glad you got this sorted out.

If you find some time, feel free to check out 4.1.2 of the SDK. It doesn't contain any simlinks anymore, so you should be able to use 7zip.

**Comment by AntiHate** [comment]
@TroubleMakerBen Thanks for the info! I'm going to try it now.

**Comment by beormalte** [comment]
I couldn't get it work either. So ended up using the archive option under the hockeyapp for mac app instead

**Comment by TroubleMakerBen** [comment]
@beormalte sorry to hear that you ran into this. Please get in touch through [Support](https://support.hockeyapp.net) if you continue to see this and we're glad to help.
