### ISSUE TITLE
Integration through Carthage without Feedback feature

### ISSUE THREAD

**Issue by ittna** [bitstadium/HockeySDK-iOS#372]
Would it be possible to make Carthage build two versions of the shared framework? Full featured one and one without Feedback feature. Users could then choose which one to integrate into their project.

This way we wouldn't need to add NSPhotoLibraryUsageDescription in case we aren't using feedback feature.

**Comment by TroubleMakerBen** [comment]
Hey @ittna,

Thanks for getting in touch and letting us know your pain points.
We've been thinking about this and we might add a target for this in the future but no promises, yet.

I'll update this issue as soon as I have news on this front.

Best,
Benjamin

**Comment by wiedem** [comment]
@TroubleMakerBen there's actually a very easy solution available if you could make one small adaptation to the _HockeySDK Framework_ target scheme.

If you disable the _HockeySDK FrameworkTests_ target for the _Run_ action people could build the SDK with all available build configurations using Carthage.
<img width="899" alt="HockeySDK Framework target scheme" src="https://cloud.githubusercontent.com/assets/18583580/22853203/1d9587ba-f050-11e6-91be-3a419637488c.png">

After this change you can simply build the SDK without the feedback feature:
`carthage build --platform iOS --configuration ReleaseCrashOnly HockeySDK-iOS`

The reason behind this is that Carthage cannot use the `archive` action to build frameworks since this action doesn't support building for the iPhone Simulator SDK. So the `build` action has to be used which uses the _Run_ setting to check which targets need to be build. Unchecking _Run_ for `HockeySDK FrameworkTests` in the scheme editor will prevent the test target from being built if you use `xcodebuild` with the `build` action.

**Comment by TroubleMakerBen** [comment]
Thanks a lot to @wiedem!

We'll make this part of the next release. It'll be out by end of this month.

**Comment by TroubleMakerBen** [comment]
Thx to the contribution and input of @wiedem it's possible to do what you are looking for.
