### ISSUE TITLE
Here is why it is empty ？？

### ISSUE THREAD

**Issue by PyXXX** [bitstadium/HockeySDK-iOS#389]
Sometimes the data is so obtained？

endTime = 1483696370249;
    exception =     {
        cause = "";      Here is why it is empty ？？
        name = "";       Here is why it is empty ？？
        signalInfo =         {
            faultAddress = "0x1176E8DD6 0 + 4688088534";
            signalCode = "#0";
            signalName = SIGABRT;
        };
    };

**Comment by TroubleMakerBen** [comment]
Hey @PyXXX,

The exception name is not guaranteed to be available at all times as there are other causes for a crash than an exception. That said, it's pretty hard to guess what you are actually asking or what issue you are running into. Can you provide more information?

Best,
Benjamin

**Comment by PyXXX** [comment]
Hey @TroubleMakerBen 

Stack:
    {"name":"","cause":"","signalInfo":{"signalCode":"TRAP_TRACE","signalName":"SIGTRAP","faultAddress":"0x104145D3D 0 + 4363410749"}}

No other more information, and only this, it looks good strange

**Comment by TroubleMakerBen** [comment]
Hey @PyXXX,

Your data just confirms what I was writing. The crash you are seeing is not caused by an exception. To familiarize yourself with crashes on iOS, I recommend [our knowledgebase](https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/which-types-of-crashes-can-be-collected-on-ios-and-os-x).
Other than that, I still don't understand what you are expecting me to do. Some more text and full sentences would help a lot ;)

Best,
Benny

**Comment by elektrojunge** [comment]
I'm closing this as I can't help with the little info that was provided.
Feel free to open this issue again but please make sure to provide more context.

Best,
Benny
