### ISSUE TITLE
Crash in [BITCrashManager setDelegate:] 

### ISSUE THREAD

**Issue by knutigro** [bitstadium/HockeySDK-iOS#392]
Hi, I have a new crash which I think is related to HockeySDK (Currently v4.1.0).

> Crashed: com.apple.main-thread
> EXC_BAD_INSTRUCTION 0x0000000001d33cef
> 
>  0x100713b60 -[BITCrashManager setDelegate:] (BITCrashManagerPrivate.h:54)

So far this crash only happened to one single user and he is on a iPhone 7 (iOS 10.2.0). What is funny is that this crash is reported 31 times  for this user, so he must have lots of patience.

By the way I got this crash from Fabric Crashalytics, as I have both Hockeyapp and Fabric in the app for the moment. HockeySDK crashreporting did not report it for some reason.

/Knut

**Comment by TroubleMakerBen** [comment]
Hi Knut,

Thank you for getting in touch. I think your issue has two different things to it, so let's try and break it down.

Let's do the easy bit first. 

> By the way I got this crash from Fabric Crashalytics, as I have both Hockeyapp and Fabric in the app for the moment. HockeySDK crashreporting did not report it for some reason.

This is actually expected behavior. It's not possible to have several crash reporting sdk in one app at the same time. This means that if you setup crash reporting with HockeyApp and Crashlytics, only one SDK will be able to install it's signal handler properly and this SDK will be able to catch the crash. Which one will be the lucky one is undefined behavior. In your case, Crashlytics was the lucky one.

Now about the crash you are seeing. `EXC_BAD_INSTRUCTION` means that an invalid memory address was accessed, possibly when you called `[BITCrashManager setDelegate:]`.
Before speculating too much about the why/how:
Could you please share your setup code? I understand that Github is public so in case you need/want to share the code in private, please do you open issue through [support](https://support.hockeyapp.net)? It'll be me who will reply to it.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
Hey @knutigro,
Sending a quick ping ;)

Benny

**Comment by TroubleMakerBen** [comment]
As I haven't heard back from you and we're not able to repro this, I'm closing this issue. Feel free to open it if it pops up for you.
