### ISSUE TITLE
Cancel update crashes the app

### ISSUE THREAD

**Issue by ovdavid** [bitstadium/HockeySDK-iOS#522]
Hi,

I'm using HockeySDK 5.1.2. On software update, when the "sdk.hockeyapp.net would like to install *myapp*" dialog comes up and I tap cancel, my app just closing without any error message whatsoever. However the "Install" button works just fine, I would like to know why could this happening.
I tested it on my ipad pro with ios 11.3 and my iphone 5 with ios 10.3.3 too.

Thanks,
David

**Comment by MatkovIvan** [comment]
Hi @ovdavid,

Thanks for getting in touch!
Unfortunately, this is a known issue that is caused by the fact that iOS doesn't provide information about the result of this dialog.

https://github.com/bitstadium/HockeySDK-iOS/blob/055f2e9804b351812c7eb25f48f538d5cf1d9970/Classes/BITUpdateManager.m#L110-L111

So, this is not a crash: the SDK just closes the app after this dialog to install an update.

Best,
Ivan

**Comment by ova-adam** [comment]
Is there a way to change the label from Cancel to Close to avoid confusing all users?

**Comment by MatkovIvan** [comment]
@ova-adam No, this is a system dialog.

**Comment by ova-adam** [comment]
So is there any other option? Can the dialog be custom rather than a system dialog?

**Comment by TroubleMakerBen** [comment]
@ova-adam there is no way for us to circumvent the system dialogue. What happens is that the SDK recognizes that a new update is available, we get the URL where to download the update and hand that information over to iOS to download & install the update. Once we hand things over to iOS, we have 0 control over alerts or, like Ivan said, what the user chose to do.
