### ISSUE TITLE
Feedback composing doesn't resize properly for keyboard

### ISSUE THREAD

**Issue by diederich** [bitstadium/HockeySDK-iOS#542]
Hey! 👋 

It seems the feedback ViewController isn't updating properly for the keyboard, at least on the X style phones. 
Here's a screen recording : https://www.dropbox.com/s/ei27nan7qcaot91/HockeyFeedback-Keyboard.MP4?dl=0

**Comment by elamalani** [comment]
@diederich Hi there, we are not making any active changes in HockeyApp at this time as we are working on [App Center](https://hockeyapp.net/) which is the future of HockeyApp. Unfortunately, we don't plan to release HockeySDK anytime soon, so this bug is unlikely to be fixed. Sorry about that. You can always fork the SDK and fix the issue if you want. 

Thank you!

**Comment by diederich** [comment]
Hey @elamalani - thanks for the heads up. 
I quickly skimmed https://docs.microsoft.com/en-us/appcenter/sdk/ but didn't see the user feedback parts in the new SDK. Is there any (public :-)) timeline for that yet?

**Comment by elamalani** [comment]
@diederich We are still discussing the Feedback feature at this point. We are weighing whether it's a more ideal experience for our customers to bring the HockeyApp functionality into App Center or instead encourage customers using the Feedback feature to use third-party integrations such as  Instabug  who have made in-app feedback their core competency.

**Comment by diederich** [comment]
That makes sense. Thanks for sharing and letting us know!
